module.exports = {
  DEFAULT_USER: 'HF_User',
  DMS_ENABLED: 4,
  WS_CONNECTION: {
    OPENED: 2,
    CLOSED: 0,
    CONNECTING: 1
  },
  PAPER_MODE_PAIRS: ['tTESTBTC:TESTUSD'],
  PAPER_MODE_CURRENCIES: new Set(['TESTBTC', 'TESTUSD']),
  WD_PACKET_DELAY: 30 * 1000,
  WD_RECONNECT_DELAY: 3 * 1000
}
